sudo: required

services:
- docker

language: go

go:
- 1.11.x

env:
- GO111MODULE=on
- GO111MODULE=on DOCKER_BUILD=1

go_import_path: github.com/midonet/midonet-kubernetes

install:
- true

script:
- ./tools/travis.sh

after_success:
- ./tools/travis_after_success.sh
