---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: translations.midonet.org
spec:
  scope: Namespaced
  group: midonet.org
  version: v1
  names:
    kind: Translation
    plural: translations
    singular: translation
    shortNames:
    - tr
  validation:
    openAPIV3Schema:
      properties:
        resources:
          type: array
          items:
            type: object
            properties:
              body:
                # JSON string
                type: string
                pattern: '^{.*}$'
              kind:
                # strings like Bridge, HostInterfacePort, IPv4MACPair
                type: string
                pattern: '^[A-Z][A-Za-z0-4]*$'
              parent:
                # UUID or an empty string
                type: string
                pattern: '^(|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: midonet-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: midonet-kube-controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: midonet-kube-controllers
  template:
    metadata:
      name: midonet-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: midonet-kube-controllers
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        prometheus.io/port: "9453"
        prometheus.io/scrape: "true"
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccountName: midonet-kube-controllers
      tolerations:
        - operator: Exists
      containers:
        - name: midonet-kube-controllers
          image: midonet/midonet-kube-controllers:1.34
          ports:
            - containerPort: 9453
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 9453
              path: /metrics
            initialDelaySeconds: 60
            failureThreshold: 6
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: MIDONETKUBE_MIDONET_API
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: midonet.api
            - name: MIDONETKUBE_MIDONET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: midonet-kube-credential
                  key: midonet.username
            - name: MIDONETKUBE_MIDONET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: midonet-kube-credential
                  key: midonet.password
            - name: MIDONETKUBE_MIDONET_PROJECT
              valueFrom:
                secretKeyRef:
                  name: midonet-kube-credential
                  key: midonet.project
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: kubernetes.endpoint.host
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: kubernetes.endpoint.port
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: midonet-kube-controllers
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: midonet-kube-controllers
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
    - midonet.org
    resources:
      - translations
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: midonet-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: midonet-kube-controllers
subjects:
- kind: ServiceAccount
  name: midonet-kube-controllers
  namespace: kube-system
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: midonet-kube-node
  namespace: kube-system
  labels:
    k8s-app: midonet-kube-node
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: midonet-kube-node
  template:
    metadata:
      labels:
        k8s-app: midonet-kube-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: midonet-kube-node
      tolerations:
        - operator: Exists
      containers:
        - name: midonet-kube-node
          image: midonet/midonet-kube-node:1.34
          securityContext:
            privileged: true
          env:
            - name: MIDONETKUBE_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MIDONETKUBE_CLUSTERCIDR
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: cluster.cidr
            - name: MIDONETKUBE_SERVICECIDR
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: service.cidr
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: kubernetes.endpoint.host
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: midonet-kube-config
                  key: kubernetes.endpoint.port
            - name: MIDONETKUBE_CNICONFIGPATH
              value: /host/etc/cni/net.d/00-midonet.conf
          volumeMounts:
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /var/run/midonet-kube-node
              name: var-run
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: var-run
          hostPath:
            path: /var/run/midonet-kube-node
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: midonet-kube-node
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: midonet-kube-node
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
    verbs:
      - get
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: midonet-kube-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: midonet-kube-node
subjects:
- kind: ServiceAccount
  name: midonet-kube-node
  namespace: kube-system

