apiVersion: apiextensions.k8s.io/v1beta1
description: MidoNet Translated Resources
kind: CustomResourceDefinition
metadata:
  name: translations.midonet.org
spec:
  scope: Namespaced
  group: midonet.org
  version: v1
  names:
    kind: Translation
    plural: translations
    singular: translation
    shortNames:
    - tr
