---
kind: ConfigMap
apiVersion: v1
metadata:
  name: midonet-kube-config
  namespace: kube-system
data:
  # Edit the following to match with your deployment.
  # kubernetes.endpoint.* should match with "kubectl get ep kubernetes".
  cluster.cidr: 10.1.0.0/16
  service.cidr: 10.96.0.0/12
  kubernetes.endpoint.host: 10.0.0.9
  kubernetes.endpoint.port: "6443"
  kubernetes.endpoint.subnet: 10.0.0.9/32
  zookeeper.endpoint: 10.0.0.9:2181
  midonet.api: http://10.0.0.9:8181/midonet-api
  midonet.router: 73302be0-4405-4cc6-a276-60b4cee1f5b9
  midonet.tunnelzone: df9feb01-8ed8-4fd4-825e-f2e039fc4bf3
---
apiVersion: v1
kind: Secret
metadata:
  name: midonet-kube-credential
  namespace: kube-system
type: Opaque
data:
  # Base64 encoded MidoNet API credential.
  # e.g.
  #   % echo -n 'mypassword' | openssl base64
  #   bXlwYXNzd29yZA==
  #   %
  midonet.username: bXluYW1l
  midonet.password: bXlwYXNzd29yZA==
  midonet.project: bXlwcm9qZWN0
